In [1]:
! pwd

/new_home/xzj23/openmmlab_workspace/SLR/src


In [2]:
from data.datasets import Phoenix2014Dataset

In [3]:
import numpy as np

gloss_dict = np.load('/new_home/xzj23/openmmlab_workspace/SLR_bak/.tmp/gloss_dict.npy', allow_pickle=True)

ddd = Phoenix2014Dataset(features_path='../data/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px',
                         annotations_path='../data/phoenix2014/phoenix-2014-multisigner/annotations/manual',
                         gloss_dict=gloss_dict.item(),
                         )

In [4]:
from torch.utils.data.dataloader import DataLoader

dl = DataLoader(ddd, batch_size=2, shuffle=True, num_workers=4, collate_fn=ddd.collate_fn, drop_last=True,
                pin_memory=True)

In [5]:
a = enumerate(dl).__next__()

In [6]:
a

(0,
 [tensor([[[[[ 0.6235,  0.5843,  0.6078,  ...,  0.6627,  0.6627,  0.6627],
             [ 0.6157,  0.6078,  0.6235,  ...,  0.6706,  0.6706,  0.6784],
             [ 0.5922,  0.6000,  0.6157,  ...,  0.6627,  0.6627,  0.6627],
             ...,
             [ 0.3098,  0.3255,  0.3176,  ...,  0.7176,  0.7333,  0.7569],
             [-0.1765, -0.1765, -0.1843,  ...,  0.6784,  0.6941,  0.7098],
             [-0.3882, -0.4039, -0.4196,  ...,  0.6471,  0.6627,  0.6863]],
  
            [[ 0.7647,  0.7412,  0.7333,  ...,  0.7412,  0.7412,  0.7412],
             [ 0.7569,  0.7490,  0.7412,  ...,  0.7412,  0.7412,  0.7490],
             [ 0.7333,  0.7490,  0.7333,  ...,  0.7333,  0.7333,  0.7333],
             ...,
             [ 0.4824,  0.4980,  0.4902,  ...,  0.8275,  0.8431,  0.8667],
             [-0.0039,  0.0039, -0.0118,  ...,  0.7882,  0.8039,  0.8196],
             [-0.2314, -0.2471, -0.2627,  ...,  0.7569,  0.7725,  0.7961]],
  
            [[ 0.9137,  0.8980,  0.8667,  ...,  0.86

In [7]:
a[0]

0

In [11]:
a[1][0].shape

torch.Size([2, 200, 3, 256, 256])

In [12]:
a[1][1].shape

torch.Size([2])

In [1]:
import yaml

with open('../configs/config.yaml', 'r') as f:
    data = yaml.load(f, Loader=yaml.FullLoader)
data

{'global': {'seed': -1},
 'wandb': {'project': 'Phoenix',
  'name': {'name': 'Test', 'splice_time': True}},
 'dataset': {'name': 'phoenix2014',
  'feature_path': '',
  'annotations_path': ''},
 'model': {'name': ''},
 'train': {'name': ''},
 'evaluation': {'name': ''}}

In [4]:
type(data)

dict

SyntaxError: invalid syntax (2817260305.py, line 1)

In [ ]:
! pwd

In [6]:
data.get('global')

{'seed': -1}

In [8]:
import types

dd = types.SimpleNamespace(**data)

In [9]:
dd

namespace(global={'seed': -1},
          wandb={'project': 'Phoenix',
                 'name': {'name': 'Test', 'splice_time': True}},
          dataset={'name': 'phoenix2014',
                   'feature_path': '',
                   'annotations_path': ''},
          model={'name': ''},
          train={'name': ''},
          evaluation={'name': ''})

In [11]:
dd.wandb

{'project': 'Phoenix', 'name': {'name': 'Test', 'splice_time': True}}

In [12]:
dd.wandb.project

AttributeError: 'dict' object has no attribute 'project'

In [1]:
import clip


In [2]:
dir(clip)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'available_models',
 'clip',
 'load',
 'model',
 'simple_tokenizer',
 'tokenize']

In [3]:
dir(clip.model)

['AttentionPool2d',
 'Bottleneck',
 'CLIP',
 'F',
 'LayerNorm',
 'ModifiedResNet',
 'OrderedDict',
 'QuickGELU',
 'ResidualAttentionBlock',
 'Transformer',
 'Tuple',
 'Union',
 'VisionTransformer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'build_model',
 'convert_weights',
 'nn',
 'np',
 'torch']

In [6]:
device = 'cuda:1'
model, preprocess = clip.load("ViT-B/32", device=device)

In [7]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_ver

In [8]:
text = clip.tokenize(["a diagram", "a dog", "a cat"]).to(device)

In [9]:
text

tensor([[49406,   320, 22697, 49407,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [49406,   320,  1929, 49407,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0, 

In [10]:
text.shape

torch.Size([3, 77])

In [14]:
model.encode_text(text)

tensor([[ 0.0547, -0.0064,  0.0492,  ..., -0.6636, -0.1276, -0.4949],
        [ 0.1443,  0.0227, -0.2915,  ..., -0.4475, -0.3416,  0.1802],
        [ 0.1978, -0.2043, -0.1533,  ..., -0.4517, -0.5659,  0.0600]],
       device='cuda:1', dtype=torch.float16, grad_fn=<MmBackward0>)

In [15]:
model

CLIP(
  (visual): VisionTransformer(
    (conv1): Conv2d(3, 768, kernel_size=(32, 32), stride=(32, 32), bias=False)
    (ln_pre): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (transformer): Transformer(
      (resblocks): Sequential(
        (0): ResidualAttentionBlock(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          )
          (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): Sequential(
            (c_fc): Linear(in_features=768, out_features=3072, bias=True)
            (gelu): QuickGELU()
            (c_proj): Linear(in_features=3072, out_features=768, bias=True)
          )
          (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
        (1): ResidualAttentionBlock(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          

In [25]:
import pandas as pd

croups = pd.read_csv('../data/phoenix2014/phoenix-2014-multisigner/annotations/manual/train.corpus.csv', sep='|')

In [29]:
croups.annotation[0]

'__ON__ LIEB ZUSCHAUER ABEND WINTER GESTERN loc-NORD SCHOTTLAND loc-REGION UEBERSCHWEMMUNG AMERIKA IX'

In [30]:
text = clip.tokenize(croups.annotation[0]).to(device)

In [31]:
text

tensor([[49406,  3838,   525,  3838, 45387,  4091,   844, 33460,   596,   806,
          2541,   619,  2945, 25826,   268, 36067,  2493,   971,   973, 25826,
           268,  4341, 16696,   867, 25324,  1028,  4334,   548, 25531,  8756,
         49407,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:1',
       dtype=torch.int32)

In [32]:
text_features = model.encode_text(text)

In [33]:
text_features

tensor([[-8.2397e-02, -1.0529e-01, -2.3633e-01, -1.5649e-01, -1.0178e-02,
         -4.4289e-03, -1.5100e-01, -4.0869e-01, -3.0835e-01,  1.9128e-01,
          5.9662e-02,  1.1182e-01,  4.4604e-01, -2.8467e-01, -1.3989e-01,
          2.2864e-01,  3.5913e-01, -4.0771e-02,  2.6538e-01,  1.4893e-01,
         -5.0635e-01, -4.2505e-01, -3.5278e-01,  3.3844e-02, -6.7505e-02,
          2.8625e-02, -4.8401e-02,  1.4824e-02, -7.9773e-02,  2.7954e-01,
          5.2917e-02, -3.7781e-02,  1.0773e-02, -3.8892e-01, -4.4556e-01,
         -4.9988e-02, -3.9819e-01, -9.1614e-02, -3.0835e-01,  3.6597e-01,
         -5.8350e-01,  2.2461e-01,  3.5217e-02, -3.3496e-01,  2.9614e-01,
         -8.1299e-02,  1.9012e-02, -3.8971e-02, -2.9526e-02,  1.6357e-01,
          1.8274e-01,  8.9417e-02,  3.1836e-01,  4.8431e-02, -1.7258e-02,
         -1.3232e-01, -4.7302e-02,  9.6741e-02,  3.5797e-02, -4.9634e-01,
         -2.5415e-01,  2.0776e-01, -4.8218e-01,  7.5989e-02, -1.1719e-01,
          2.1155e-01,  2.6514e-01, -8.

In [34]:
text_features.shape

torch.Size([1, 512])

In [2]:
import hydra
from omegaconf import DictConfig


@hydra.main(version_base=None, config_path='../configs', config_name='config')
def main(cfg: DictConfig):
    print(cfg)


if __name__ == '__main__':
    main()

usage: ipykernel_launcher.py [--help] [--hydra-help] [--version]
                             [--cfg {job,hydra,all}] [--resolve]
                             [--package PACKAGE] [--run] [--multirun]
                             [--shell-completion] [--config-path CONFIG_PATH]
                             [--config-name CONFIG_NAME]
                             [--config-dir CONFIG_DIR]
                             [--experimental-rerun EXPERIMENTAL_RERUN]
                             [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                             [overrides ...]
ipykernel_launcher.py: error: unrecognized arguments: -f


SystemExit: 2