In [1]:
import os
import cv2
import numpy as np
import torch
from spacy.compat import pickle
from torchvision.transforms import ToTensor
# from slr.datasets.transforms import ToTensor
import pickle

In [2]:
img_file = "/new_home/xzj23/workspace/SLR/data/phoenix2014/phoenix-2014-multisigner/features/fullFrame-210x260px/train/01April_2010_Thursday_heute_default-0/1/01April_2010_Thursday_heute.avi_pid0_fn000000-0.png"
npy_frame_file = "f.npy"
save_file = "./img_test.pt"
np_save_file = "./img_test.npy"

print(os.path.getsize(img_file) / 1024, "KB")

46.4140625 KB


In [3]:
frame = cv2.imread(img_file)
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

In [4]:
np.save(npy_frame_file, frame)
print(os.path.getsize(npy_frame_file) // 1024, "KB")

160 KB


In [5]:
t = ToTensor()(frame)

In [6]:
t.shape

torch.Size([3, 260, 210])

In [7]:
t.dtype

torch.float32

In [8]:
t

tensor([[[0.7882, 0.7804, 0.8196,  ..., 0.8078, 0.8157, 0.8235],
         [0.8118, 0.8275, 0.8078,  ..., 0.8235, 0.8157, 0.8235],
         [0.8118, 0.8275, 0.8078,  ..., 0.8235, 0.8235, 0.8235],
         ...,
         [0.5412, 0.5490, 0.6000,  ..., 0.8549, 0.8588, 0.8863],
         [0.2902, 0.2863, 0.3451,  ..., 0.8353, 0.8431, 0.8627],
         [0.1373, 0.1255, 0.1765,  ..., 0.8196, 0.8235, 0.8471]],

        [[0.9098, 0.9020, 0.8706,  ..., 0.8588, 0.8667, 0.8745],
         [0.8549, 0.8706, 0.8627,  ..., 0.8667, 0.8588, 0.8667],
         [0.8549, 0.8706, 0.8627,  ..., 0.8667, 0.8667, 0.8667],
         ...,
         [0.7216, 0.7294, 0.7137,  ..., 0.9098, 0.9137, 0.9412],
         [0.4706, 0.4667, 0.4588,  ..., 0.8902, 0.8980, 0.9176],
         [0.3176, 0.3059, 0.3216,  ..., 0.8745, 0.8784, 0.9020]],

        [[0.9686, 0.9608, 0.9294,  ..., 0.9176, 0.9255, 0.9333],
         [0.8980, 0.9137, 0.9098,  ..., 0.9176, 0.9098, 0.9176],
         [0.8980, 0.9137, 0.9098,  ..., 0.9176, 0.9176, 0.

In [9]:
torch.save(t.to(torch.float16), save_file, pickle_protocol=pickle.HIGHEST_PROTOCOL)

In [10]:
print(os.path.getsize(save_file) // 1024, "KB")

320 KB


In [11]:
npy_data = t.numpy()

In [12]:
tt = torch.load(save_file)

In [13]:
tt

tensor([[[0.7881, 0.7803, 0.8198,  ..., 0.8076, 0.8159, 0.8237],
         [0.8115, 0.8276, 0.8076,  ..., 0.8237, 0.8159, 0.8237],
         [0.8115, 0.8276, 0.8076,  ..., 0.8237, 0.8237, 0.8237],
         ...,
         [0.5410, 0.5488, 0.6001,  ..., 0.8550, 0.8589, 0.8862],
         [0.2903, 0.2864, 0.3452,  ..., 0.8354, 0.8433, 0.8628],
         [0.1372, 0.1255, 0.1765,  ..., 0.8198, 0.8237, 0.8472]],

        [[0.9097, 0.9019, 0.8706,  ..., 0.8589, 0.8667, 0.8745],
         [0.8550, 0.8706, 0.8628,  ..., 0.8667, 0.8589, 0.8667],
         [0.8550, 0.8706, 0.8628,  ..., 0.8667, 0.8667, 0.8667],
         ...,
         [0.7217, 0.7295, 0.7139,  ..., 0.9097, 0.9136, 0.9414],
         [0.4707, 0.4666, 0.4587,  ..., 0.8901, 0.8979, 0.9175],
         [0.3176, 0.3059, 0.3215,  ..., 0.8745, 0.8784, 0.9019]],

        [[0.9688, 0.9609, 0.9292,  ..., 0.9175, 0.9253, 0.9331],
         [0.8979, 0.9136, 0.9097,  ..., 0.9175, 0.9097, 0.9175],
         [0.8979, 0.9136, 0.9097,  ..., 0.9175, 0.9175, 0.

In [14]:
tt.shape

torch.Size([3, 260, 210])

In [15]:
tt.dtype

torch.float16

In [16]:
np.save(np_save_file, npy_data)

In [17]:
print(os.path.getsize(np_save_file) // 1024, "KB")

639 KB


In [18]:
import torch
import h5py

h5py_file = "test.h5"

with h5py.File(h5py_file, 'w') as f:
    f.create_dataset('data', data=t.to(torch.float16).numpy(), compression='gzip', compression_opts=9)

In [19]:
print(os.path.getsize(h5py_file) // 1024, "KB")

108 KB


In [21]:
with h5py.File("/new_home/xzj23/workspace/SLR/data/preprocess/ttt/train/01April_2010_Thursday_heute_default-0/1/video.h5", 'r') as f:
    data = f['data'][:]
data

array([[[[-0.9937, -0.9937, -0.9937, ..., -0.9937, -0.9937, -0.9937],
         [-0.9937, -0.9937, -0.9937, ..., -0.9937, -0.9937, -0.9937],
         [-0.9937, -0.9937, -0.9937, ..., -0.9937, -0.9937, -0.9937],
         ...,
         [-0.9956, -0.9956, -0.9956, ..., -0.993 , -0.993 , -0.993 ],
         [-0.9976, -0.9976, -0.9976, ..., -0.9937, -0.993 , -0.993 ],
         [-0.999 , -0.999 , -0.999 , ..., -0.9937, -0.9937, -0.993 ]],

        [[-0.9927, -0.9927, -0.993 , ..., -0.993 , -0.993 , -0.993 ],
         [-0.993 , -0.993 , -0.993 , ..., -0.993 , -0.993 , -0.993 ],
         [-0.993 , -0.993 , -0.993 , ..., -0.993 , -0.993 , -0.993 ],
         ...,
         [-0.994 , -0.994 , -0.994 , ..., -0.9927, -0.9927, -0.9927],
         [-0.996 , -0.996 , -0.996 , ..., -0.993 , -0.9927, -0.9927],
         [-0.9976, -0.9976, -0.9976, ..., -0.993 , -0.993 , -0.993 ]],

        [[-0.992 , -0.9927, -0.9927, ..., -0.9927, -0.9927, -0.9927],
         [-0.993 , -0.9927, -0.9927, ..., -0.9927, -0.9927

In [22]:
type(data)

numpy.ndarray

In [27]:
# ToTensor()(data)

In [23]:
data.shape

(176, 3, 256, 256)